---
abstract: 'Acmeist Documentation Toolset'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Stardoc
name: Stardoc
no_index:
  directory:
    - inc
    - t
requires:
  IO::All: 0.41
  Mouse: 0.92
  Template::Toolkit::Simple: 0.13
  YAML::XS: 0.35
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.15
